### ISSUE TITLE
Issue w/ read_emails()

### ISSUE THREAD

**Issue by BotezanTechnologic** [riensen/Auto-GPT-Email-Plugin#12]
SYSTEM:  Command read_emails returned: Error: decode() argument 'encoding' must be str, not None

Auto-GPT is throwing this error when it attempts to read_emails() and fetch any of my recent mails for processing or replies. 

I believe the Imap/smtp is configured properly as I was able to send an email out with auto-gpt, but I could be wrong. 

Also attempted some work-arounds in the python code, but was unsuccessful after a few different attempts. 

Using 2FA w/ app password setup.

**Comment by riensen** [comment]
Thanks for the bug report. Can you let me know, what parameters Auto-GPT is using when calling the read_email command? A screenshot also works.

**Comment by riensen** [comment]
@BotezanTechnologic in addition I extended the imap search parameter such that more complex imap searches can be handled. This might resolve the issue.

**Comment by runquik** [comment]
Also testing this. Send email works pretty well but I'm also getting the permissions errors when trying to read emails. Also getting a permission error when trying to attach a file:
![image](https://user-images.githubusercontent.com/130519296/235365933-01e5f5dc-d8a0-48c8-8d56-b702b54a2455.png)

**Comment by runquik** [comment]
Oh, here are a couple of shots from the read_emails command:
![image](https://user-images.githubusercontent.com/130519296/235366176-d792ae39-0194-4578-8c2c-3676bac60b75.png)

![image](https://user-images.githubusercontent.com/130519296/235366202-981df9d9-5e52-421d-9f56-b487b0a8aa6e.png)

**Comment by tudorbotezan** [comment]
Thanks for looking into this @riensen ! Appreciate you already pushing a possible fix, my bad on not replying till now. 

When testing this I was just using the same test setup as in the docs. 

Will test with the updated imap params later today and let you know what happens. 
If it throws another error, I will provide screenshots.

**Comment by tudorbotezan** [comment]
Confirmed fixed & working on my end ✅

Thank you @riensen !

**Comment by riensen** [comment]
> Oh, here are a couple of shots from the read_emails command:
> 
> ![image](https://user-images.githubusercontent.com/130519296/235366176-d792ae39-0194-4578-8c2c-3676bac60b75.png)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/130519296/235366202-981df9d9-5e52-421d-9f56-b487b0a8aa6e.png)
> 
> 
> 
> 
> 
> 

Auto-GPT seems to try to pass additional parameters to the read emails function. There is nothing that can be done to fix this within the plug-in. Its a problem within Auto-GPT (GPT not following directions).

**Comment by riensen** [comment]
@BotezanTechnologic Thanks for confirming!

**Comment by runquik** [comment]
@BotezanTechnologic can you tell me what you did to fix? I'm using the latest imap config and still having the same error

**Comment by tudorbotezan** [comment]
@runquik just updated with the new changes that got pushed. I don't think you and I were experiencing the same error.
