### ISSUE TITLE
AI using "to" instead of "recipient" and "body" instead of "message"

### ISSUE THREAD

**Issue by finster869** [riensen/Auto-GPT-Email-Plugin#6]
Whenever the AI uses send_email, it uses "to" instead of "recipient" and "body" instead of "message". I then have to tell it through the console to use "recipient" and "message" in order for it to send the email.  Does anybody else have this issue?  Any ideas how to fix it?

**Comment by Eeasonn** [comment]
Yeah.. I've encountered the same problem, waiting for solve

**Comment by riensen** [comment]
Please retry with the latest version

**Comment by finster869** [comment]
Hi Riensen. Thanks for taking a look at it. Unfortunately, I am still having the same issue. It tries to send the email to "to" instead of recipient and uses "body" instead of "message" resulting in an error.  If I input to use recipient and message, it ultimately works, but takes multiple tries.

**Comment by riensen** [comment]
Have you used the current version, zipped it again and put it in the plugins folder?
It should now only accept `to` and ` body`:
https://github.com/riensen/Auto-GPT-Email-Plugin/blob/master/src/autogpt_plugins/email/__init__.py#L46

In fact using `message`  should give an error now

**Comment by finster869** [comment]
Yes, it now works for me. Although I updated the code via Github desktop, I had forgotten to move the zip file into the correct folder.  It now works perfectly.  Thanks for all of your efforts!!!!
