### ISSUE TITLE
Recent changes in AutoGPT broke 

### ISSUE THREAD

**Issue by ppetermann** [riensen/Auto-GPT-Email-Plugin#9]
https://github.com/Significant-Gravitas/Auto-GPT/pull/2982 removed autogpt.path_in_workspace, breaking attachments, as those make use of this

**Comment by riensen** [comment]
Thanks, I will take a look at this

**Comment by riensen** [comment]
Thanks again for the issue. https://github.com/riensen/Auto-GPT-Email-Plugin/commit/22f6e50a410ab3947fd44a59dc9cc904bbfb22b9 should address this.
